### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by cxw-droid** [diningphil/gnn-comparison#29]
Thank you for sharing the code. I found an error when I tried to preprocess the data.

> Traceback (most recent call last):
  File "PrepareDatasets.py", line 73, in <module>
    preprocess_dataset(dataset_name, args_dict)
  File "PrepareDatasets.py", line 60, in preprocess_dataset
    dataset_class(**args_dict)
  File "/home/xxx/code/gnn-comparison/datasets/manager.py", line 75, in __init__
    self.processed_dir / f"{self.name}.pt"))
  File "/home/xxx/miniconda3/envs/torch1.4.0/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/xxx/miniconda3/envs/torch1.4.0/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
AttributeError: 'PosixPath' object has no attribute 'tell'

I installed torch 1.4.0 etc. following the instructions. Can you please take a look at this issue? Thanks.

**Comment by diningphil** [comment]
Sorry if I did not answer in time. I hope you solved the issue, if not feel free to reopen it!
F.
